package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChiTietPhieuMuon generated by hbm2java
 */
@Entity
@Table(name="ChiTietPhieuMuon"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class ChiTietPhieuMuon  implements java.io.Serializable {


     private int maChiTietPhieuMuon;
     private PhieuMuon phieuMuon;
     private Sach sach;
     private Date ngayTra;
     private Date ngayMuon;
     private Integer lanMuon;
     private Set<Phat> phats = new HashSet<Phat>(0);

    public ChiTietPhieuMuon() {
    }

	
    public ChiTietPhieuMuon(int maChiTietPhieuMuon) {
        this.maChiTietPhieuMuon = maChiTietPhieuMuon;
    }
    public ChiTietPhieuMuon(int maChiTietPhieuMuon, PhieuMuon phieuMuon, Sach sach, Date ngayTra, Date ngayMuon, Integer lanMuon, Set<Phat> phats) {
       this.maChiTietPhieuMuon = maChiTietPhieuMuon;
       this.phieuMuon = phieuMuon;
       this.sach = sach;
       this.ngayTra = ngayTra;
       this.ngayMuon = ngayMuon;
       this.lanMuon = lanMuon;
       this.phats = phats;
    }
   
     @Id 

    
    @Column(name="MaChiTietPhieuMuon", unique=true, nullable=false)
    public int getMaChiTietPhieuMuon() {
        return this.maChiTietPhieuMuon;
    }
    
    public void setMaChiTietPhieuMuon(int maChiTietPhieuMuon) {
        this.maChiTietPhieuMuon = maChiTietPhieuMuon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaPhieuMuon")
    public PhieuMuon getPhieuMuon() {
        return this.phieuMuon;
    }
    
    public void setPhieuMuon(PhieuMuon phieuMuon) {
        this.phieuMuon = phieuMuon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaSach")
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NgayTra", length=23)
    public Date getNgayTra() {
        return this.ngayTra;
    }
    
    public void setNgayTra(Date ngayTra) {
        this.ngayTra = ngayTra;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NgayMuon", length=23)
    public Date getNgayMuon() {
        return this.ngayMuon;
    }
    
    public void setNgayMuon(Date ngayMuon) {
        this.ngayMuon = ngayMuon;
    }

    
    @Column(name="LanMuon")
    public Integer getLanMuon() {
        return this.lanMuon;
    }
    
    public void setLanMuon(Integer lanMuon) {
        this.lanMuon = lanMuon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chiTietPhieuMuon")
    public Set<Phat> getPhats() {
        return this.phats;
    }
    
    public void setPhats(Set<Phat> phats) {
        this.phats = phats;
    }




}


