package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChiTietDonHang generated by hbm2java
 */
@Entity
@Table(name="ChiTietDonHang"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class ChiTietDonHang  implements java.io.Serializable {


     private int maChiTietDonHang;
     private DonHang donHang;
     private NhaXuatBan nhaXuatBan;
     private Integer stt;
     private Serializable tenSach;
     private Serializable nhanDeChinh;
     private Serializable nhanDePhu;
     private Double gia;
     private Integer soCuon;
     private Integer soTrang;
     private Serializable kichThuoc;
     private Serializable ngonNgu;
     private Integer namXuatBan;
     private Date ngayMua;
     private Date ngayGiao;
     private Date ngayGiaoThucTe;
     private Serializable tacGia;
     private Integer cuon;
     private Integer tap;

    public ChiTietDonHang() {
    }

	
    public ChiTietDonHang(int maChiTietDonHang) {
        this.maChiTietDonHang = maChiTietDonHang;
    }
    public ChiTietDonHang(int maChiTietDonHang, DonHang donHang, NhaXuatBan nhaXuatBan, Integer stt, Serializable tenSach, Serializable nhanDeChinh, Serializable nhanDePhu, Double gia, Integer soCuon, Integer soTrang, Serializable kichThuoc, Serializable ngonNgu, Integer namXuatBan, Date ngayMua, Date ngayGiao, Date ngayGiaoThucTe, Serializable tacGia, Integer cuon, Integer tap) {
       this.maChiTietDonHang = maChiTietDonHang;
       this.donHang = donHang;
       this.nhaXuatBan = nhaXuatBan;
       this.stt = stt;
       this.tenSach = tenSach;
       this.nhanDeChinh = nhanDeChinh;
       this.nhanDePhu = nhanDePhu;
       this.gia = gia;
       this.soCuon = soCuon;
       this.soTrang = soTrang;
       this.kichThuoc = kichThuoc;
       this.ngonNgu = ngonNgu;
       this.namXuatBan = namXuatBan;
       this.ngayMua = ngayMua;
       this.ngayGiao = ngayGiao;
       this.ngayGiaoThucTe = ngayGiaoThucTe;
       this.tacGia = tacGia;
       this.cuon = cuon;
       this.tap = tap;
    }
   
     @Id 

    
    @Column(name="MaChiTietDonHang", unique=true, nullable=false)
    public int getMaChiTietDonHang() {
        return this.maChiTietDonHang;
    }
    
    public void setMaChiTietDonHang(int maChiTietDonHang) {
        this.maChiTietDonHang = maChiTietDonHang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaDonHang")
    public DonHang getDonHang() {
        return this.donHang;
    }
    
    public void setDonHang(DonHang donHang) {
        this.donHang = donHang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NhaXuatBan")
    public NhaXuatBan getNhaXuatBan() {
        return this.nhaXuatBan;
    }
    
    public void setNhaXuatBan(NhaXuatBan nhaXuatBan) {
        this.nhaXuatBan = nhaXuatBan;
    }

    
    @Column(name="Stt")
    public Integer getStt() {
        return this.stt;
    }
    
    public void setStt(Integer stt) {
        this.stt = stt;
    }

    
    @Column(name="TenSach")
    public Serializable getTenSach() {
        return this.tenSach;
    }
    
    public void setTenSach(Serializable tenSach) {
        this.tenSach = tenSach;
    }

    
    @Column(name="NhanDeChinh")
    public Serializable getNhanDeChinh() {
        return this.nhanDeChinh;
    }
    
    public void setNhanDeChinh(Serializable nhanDeChinh) {
        this.nhanDeChinh = nhanDeChinh;
    }

    
    @Column(name="NhanDePhu")
    public Serializable getNhanDePhu() {
        return this.nhanDePhu;
    }
    
    public void setNhanDePhu(Serializable nhanDePhu) {
        this.nhanDePhu = nhanDePhu;
    }

    
    @Column(name="Gia", precision=53, scale=0)
    public Double getGia() {
        return this.gia;
    }
    
    public void setGia(Double gia) {
        this.gia = gia;
    }

    
    @Column(name="SoCuon")
    public Integer getSoCuon() {
        return this.soCuon;
    }
    
    public void setSoCuon(Integer soCuon) {
        this.soCuon = soCuon;
    }

    
    @Column(name="SoTrang")
    public Integer getSoTrang() {
        return this.soTrang;
    }
    
    public void setSoTrang(Integer soTrang) {
        this.soTrang = soTrang;
    }

    
    @Column(name="KichThuoc")
    public Serializable getKichThuoc() {
        return this.kichThuoc;
    }
    
    public void setKichThuoc(Serializable kichThuoc) {
        this.kichThuoc = kichThuoc;
    }

    
    @Column(name="NgonNgu")
    public Serializable getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(Serializable ngonNgu) {
        this.ngonNgu = ngonNgu;
    }

    
    @Column(name="NamXuatBan")
    public Integer getNamXuatBan() {
        return this.namXuatBan;
    }
    
    public void setNamXuatBan(Integer namXuatBan) {
        this.namXuatBan = namXuatBan;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayMua", length=10)
    public Date getNgayMua() {
        return this.ngayMua;
    }
    
    public void setNgayMua(Date ngayMua) {
        this.ngayMua = ngayMua;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayGiao", length=10)
    public Date getNgayGiao() {
        return this.ngayGiao;
    }
    
    public void setNgayGiao(Date ngayGiao) {
        this.ngayGiao = ngayGiao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayGiaoThucTe", length=10)
    public Date getNgayGiaoThucTe() {
        return this.ngayGiaoThucTe;
    }
    
    public void setNgayGiaoThucTe(Date ngayGiaoThucTe) {
        this.ngayGiaoThucTe = ngayGiaoThucTe;
    }

    
    @Column(name="TacGia")
    public Serializable getTacGia() {
        return this.tacGia;
    }
    
    public void setTacGia(Serializable tacGia) {
        this.tacGia = tacGia;
    }

    
    @Column(name="Cuon")
    public Integer getCuon() {
        return this.cuon;
    }
    
    public void setCuon(Integer cuon) {
        this.cuon = cuon;
    }

    
    @Column(name="Tap")
    public Integer getTap() {
        return this.tap;
    }
    
    public void setTap(Integer tap) {
        this.tap = tap;
    }




}


