package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonHang generated by hbm2java
 */
@Entity
@Table(name="DonHang"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class DonHang  implements java.io.Serializable {


     private int maDonHang;
     private NhanVien nhanVien;
     private Double tongTien;
     private Date ngayMua;
     private Set<ChiTietDonHang> chiTietDonHangs = new HashSet<ChiTietDonHang>(0);

    public DonHang() {
    }

	
    public DonHang(int maDonHang) {
        this.maDonHang = maDonHang;
    }
    public DonHang(int maDonHang, NhanVien nhanVien, Double tongTien, Date ngayMua, Set<ChiTietDonHang> chiTietDonHangs) {
       this.maDonHang = maDonHang;
       this.nhanVien = nhanVien;
       this.tongTien = tongTien;
       this.ngayMua = ngayMua;
       this.chiTietDonHangs = chiTietDonHangs;
    }
   
     @Id 

    
    @Column(name="MaDonHang", unique=true, nullable=false)
    public int getMaDonHang() {
        return this.maDonHang;
    }
    
    public void setMaDonHang(int maDonHang) {
        this.maDonHang = maDonHang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NhanVienLap")
    public NhanVien getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }

    
    @Column(name="TongTien", precision=53, scale=0)
    public Double getTongTien() {
        return this.tongTien;
    }
    
    public void setTongTien(Double tongTien) {
        this.tongTien = tongTien;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayMua", length=10)
    public Date getNgayMua() {
        return this.ngayMua;
    }
    
    public void setNgayMua(Date ngayMua) {
        this.ngayMua = ngayMua;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="donHang")
    public Set<ChiTietDonHang> getChiTietDonHangs() {
        return this.chiTietDonHangs;
    }
    
    public void setChiTietDonHangs(Set<ChiTietDonHang> chiTietDonHangs) {
        this.chiTietDonHangs = chiTietDonHangs;
    }




}


