package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GopY generated by hbm2java
 */
@Entity
@Table(name="GopY"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class GopY  implements java.io.Serializable {


     private int maGopY;
     private NguoiDung nguoiDung;
     private Serializable nguoiGopY;
     private Date timeGopY;
     private Serializable email;
     private String noiDungGopY;
     private Boolean daXem;

    public GopY() {
    }

	
    public GopY(int maGopY) {
        this.maGopY = maGopY;
    }
    public GopY(int maGopY, NguoiDung nguoiDung, Serializable nguoiGopY, Date timeGopY, Serializable email, String noiDungGopY, Boolean daXem) {
       this.maGopY = maGopY;
       this.nguoiDung = nguoiDung;
       this.nguoiGopY = nguoiGopY;
       this.timeGopY = timeGopY;
       this.email = email;
       this.noiDungGopY = noiDungGopY;
       this.daXem = daXem;
    }
   
     @Id 

    
    @Column(name="MaGopY", unique=true, nullable=false)
    public int getMaGopY() {
        return this.maGopY;
    }
    
    public void setMaGopY(int maGopY) {
        this.maGopY = maGopY;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NguoiDungGopY")
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }
    
    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }

    
    @Column(name="NguoiGopY")
    public Serializable getNguoiGopY() {
        return this.nguoiGopY;
    }
    
    public void setNguoiGopY(Serializable nguoiGopY) {
        this.nguoiGopY = nguoiGopY;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TimeGopY", length=23)
    public Date getTimeGopY() {
        return this.timeGopY;
    }
    
    public void setTimeGopY(Date timeGopY) {
        this.timeGopY = timeGopY;
    }

    
    @Column(name="Email")
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }

    
    @Column(name="NoiDungGopY")
    public String getNoiDungGopY() {
        return this.noiDungGopY;
    }
    
    public void setNoiDungGopY(String noiDungGopY) {
        this.noiDungGopY = noiDungGopY;
    }

    
    @Column(name="DaXem")
    public Boolean getDaXem() {
        return this.daXem;
    }
    
    public void setDaXem(Boolean daXem) {
        this.daXem = daXem;
    }




}


