package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NguoiDung generated by hbm2java
 */
@Entity
@Table(name="NguoiDung"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class NguoiDung  implements java.io.Serializable {


     private int maNguoiDung;
     private Serializable hoTen;
     private String soCmnd;
     private Date ngaySinh;
     private Serializable mssv;
     private Date ngayHetHan;
     private Serializable loaiNd;
     private Serializable tenDangNhap;
     private Serializable matKhau;
     private Date ngayDangKy;
     private Set<PhieuMuon> phieuMuons = new HashSet<PhieuMuon>(0);
     private Set<GopY> gopYs = new HashSet<GopY>(0);

    public NguoiDung() {
    }

	
    public NguoiDung(int maNguoiDung) {
        this.maNguoiDung = maNguoiDung;
    }
    public NguoiDung(int maNguoiDung, Serializable hoTen, String soCmnd, Date ngaySinh, Serializable mssv, Date ngayHetHan, Serializable loaiNd, Serializable tenDangNhap, Serializable matKhau, Date ngayDangKy, Set<PhieuMuon> phieuMuons, Set<GopY> gopYs) {
       this.maNguoiDung = maNguoiDung;
       this.hoTen = hoTen;
       this.soCmnd = soCmnd;
       this.ngaySinh = ngaySinh;
       this.mssv = mssv;
       this.ngayHetHan = ngayHetHan;
       this.loaiNd = loaiNd;
       this.tenDangNhap = tenDangNhap;
       this.matKhau = matKhau;
       this.ngayDangKy = ngayDangKy;
       this.phieuMuons = phieuMuons;
       this.gopYs = gopYs;
    }
   
     @Id 

    
    @Column(name="MaNguoiDung", unique=true, nullable=false)
    public int getMaNguoiDung() {
        return this.maNguoiDung;
    }
    
    public void setMaNguoiDung(int maNguoiDung) {
        this.maNguoiDung = maNguoiDung;
    }

    
    @Column(name="HoTen")
    public Serializable getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(Serializable hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="SoCMND", length=9)
    public String getSoCmnd() {
        return this.soCmnd;
    }
    
    public void setSoCmnd(String soCmnd) {
        this.soCmnd = soCmnd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgaySinh", length=10)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    
    @Column(name="MSSV")
    public Serializable getMssv() {
        return this.mssv;
    }
    
    public void setMssv(Serializable mssv) {
        this.mssv = mssv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayHetHan", length=10)
    public Date getNgayHetHan() {
        return this.ngayHetHan;
    }
    
    public void setNgayHetHan(Date ngayHetHan) {
        this.ngayHetHan = ngayHetHan;
    }

    
    @Column(name="LoaiND")
    public Serializable getLoaiNd() {
        return this.loaiNd;
    }
    
    public void setLoaiNd(Serializable loaiNd) {
        this.loaiNd = loaiNd;
    }

    
    @Column(name="TenDangNhap")
    public Serializable getTenDangNhap() {
        return this.tenDangNhap;
    }
    
    public void setTenDangNhap(Serializable tenDangNhap) {
        this.tenDangNhap = tenDangNhap;
    }

    
    @Column(name="MatKhau")
    public Serializable getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(Serializable matKhau) {
        this.matKhau = matKhau;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgayDangKy", length=10)
    public Date getNgayDangKy() {
        return this.ngayDangKy;
    }
    
    public void setNgayDangKy(Date ngayDangKy) {
        this.ngayDangKy = ngayDangKy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nguoiDung")
    public Set<PhieuMuon> getPhieuMuons() {
        return this.phieuMuons;
    }
    
    public void setPhieuMuons(Set<PhieuMuon> phieuMuons) {
        this.phieuMuons = phieuMuons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nguoiDung")
    public Set<GopY> getGopYs() {
        return this.gopYs;
    }
    
    public void setGopYs(Set<GopY> gopYs) {
        this.gopYs = gopYs;
    }




}


