package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name="NhanVien"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class NhanVien  implements java.io.Serializable {


     private int maNhanVien;
     private Serializable hoTen;
     private String cmnd;
     private Date ngaySinh;
     private Serializable loaiNv;
     private Serializable sdt;
     private Serializable tenDangNhap;
     private Serializable matKhau;
     private Set<DonHang> donHangs = new HashSet<DonHang>(0);
     private Set<PhieuMuon> phieuMuons = new HashSet<PhieuMuon>(0);

    public NhanVien() {
    }

	
    public NhanVien(int maNhanVien) {
        this.maNhanVien = maNhanVien;
    }
    public NhanVien(int maNhanVien, Serializable hoTen, String cmnd, Date ngaySinh, Serializable loaiNv, Serializable sdt, Serializable tenDangNhap, Serializable matKhau, Set<DonHang> donHangs, Set<PhieuMuon> phieuMuons) {
       this.maNhanVien = maNhanVien;
       this.hoTen = hoTen;
       this.cmnd = cmnd;
       this.ngaySinh = ngaySinh;
       this.loaiNv = loaiNv;
       this.sdt = sdt;
       this.tenDangNhap = tenDangNhap;
       this.matKhau = matKhau;
       this.donHangs = donHangs;
       this.phieuMuons = phieuMuons;
    }
   
     @Id 

    
    @Column(name="MaNhanVien", unique=true, nullable=false)
    public int getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(int maNhanVien) {
        this.maNhanVien = maNhanVien;
    }

    
    @Column(name="HoTen")
    public Serializable getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(Serializable hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="CMND", length=9)
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NgaySinh", length=10)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    
    @Column(name="LoaiNV")
    public Serializable getLoaiNv() {
        return this.loaiNv;
    }
    
    public void setLoaiNv(Serializable loaiNv) {
        this.loaiNv = loaiNv;
    }

    
    @Column(name="SDT")
    public Serializable getSdt() {
        return this.sdt;
    }
    
    public void setSdt(Serializable sdt) {
        this.sdt = sdt;
    }

    
    @Column(name="TenDangNhap")
    public Serializable getTenDangNhap() {
        return this.tenDangNhap;
    }
    
    public void setTenDangNhap(Serializable tenDangNhap) {
        this.tenDangNhap = tenDangNhap;
    }

    
    @Column(name="MatKhau")
    public Serializable getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(Serializable matKhau) {
        this.matKhau = matKhau;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanVien")
    public Set<DonHang> getDonHangs() {
        return this.donHangs;
    }
    
    public void setDonHangs(Set<DonHang> donHangs) {
        this.donHangs = donHangs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanVien")
    public Set<PhieuMuon> getPhieuMuons() {
        return this.phieuMuons;
    }
    
    public void setPhieuMuons(Set<PhieuMuon> phieuMuons) {
        this.phieuMuons = phieuMuons;
    }




}


