package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phat generated by hbm2java
 */
@Entity
@Table(name="Phat"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Phat  implements java.io.Serializable {


     private int maPhat;
     private ChiTietPhieuMuon chiTietPhieuMuon;
     private QuyDinhPhat quyDinhPhat;
     private Date ngayNopPhat;
     private Double soTienNop;
     private Integer nguoiThu;

    public Phat() {
    }

	
    public Phat(int maPhat) {
        this.maPhat = maPhat;
    }
    public Phat(int maPhat, ChiTietPhieuMuon chiTietPhieuMuon, QuyDinhPhat quyDinhPhat, Date ngayNopPhat, Double soTienNop, Integer nguoiThu) {
       this.maPhat = maPhat;
       this.chiTietPhieuMuon = chiTietPhieuMuon;
       this.quyDinhPhat = quyDinhPhat;
       this.ngayNopPhat = ngayNopPhat;
       this.soTienNop = soTienNop;
       this.nguoiThu = nguoiThu;
    }
   
     @Id 

    
    @Column(name="MaPhat", unique=true, nullable=false)
    public int getMaPhat() {
        return this.maPhat;
    }
    
    public void setMaPhat(int maPhat) {
        this.maPhat = maPhat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ChiTietPhieuMuon")
    public ChiTietPhieuMuon getChiTietPhieuMuon() {
        return this.chiTietPhieuMuon;
    }
    
    public void setChiTietPhieuMuon(ChiTietPhieuMuon chiTietPhieuMuon) {
        this.chiTietPhieuMuon = chiTietPhieuMuon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="QuyDinhPhat")
    public QuyDinhPhat getQuyDinhPhat() {
        return this.quyDinhPhat;
    }
    
    public void setQuyDinhPhat(QuyDinhPhat quyDinhPhat) {
        this.quyDinhPhat = quyDinhPhat;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NgayNopPhat", length=23)
    public Date getNgayNopPhat() {
        return this.ngayNopPhat;
    }
    
    public void setNgayNopPhat(Date ngayNopPhat) {
        this.ngayNopPhat = ngayNopPhat;
    }

    
    @Column(name="SoTienNop", precision=53, scale=0)
    public Double getSoTienNop() {
        return this.soTienNop;
    }
    
    public void setSoTienNop(Double soTienNop) {
        this.soTienNop = soTienNop;
    }

    
    @Column(name="NguoiThu")
    public Integer getNguoiThu() {
        return this.nguoiThu;
    }
    
    public void setNguoiThu(Integer nguoiThu) {
        this.nguoiThu = nguoiThu;
    }




}


