package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhieuMuon generated by hbm2java
 */
@Entity
@Table(name="PhieuMuon"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class PhieuMuon  implements java.io.Serializable {


     private int maPhieuMuon;
     private NguoiDung nguoiDung;
     private NhanVien nhanVien;
     private Date ngayMuon;
     private Date ngayTra;
     private Integer soLuongSach;
     private Integer tinhTrangMuon;
     private Set<ChiTietPhieuMuon> chiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>(0);

    public PhieuMuon() {
    }

	
    public PhieuMuon(int maPhieuMuon) {
        this.maPhieuMuon = maPhieuMuon;
    }
    public PhieuMuon(int maPhieuMuon, NguoiDung nguoiDung, NhanVien nhanVien, Date ngayMuon, Date ngayTra, Integer soLuongSach, Integer tinhTrangMuon, Set<ChiTietPhieuMuon> chiTietPhieuMuons) {
       this.maPhieuMuon = maPhieuMuon;
       this.nguoiDung = nguoiDung;
       this.nhanVien = nhanVien;
       this.ngayMuon = ngayMuon;
       this.ngayTra = ngayTra;
       this.soLuongSach = soLuongSach;
       this.tinhTrangMuon = tinhTrangMuon;
       this.chiTietPhieuMuons = chiTietPhieuMuons;
    }
   
     @Id 

    
    @Column(name="MaPhieuMuon", unique=true, nullable=false)
    public int getMaPhieuMuon() {
        return this.maPhieuMuon;
    }
    
    public void setMaPhieuMuon(int maPhieuMuon) {
        this.maPhieuMuon = maPhieuMuon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NguoiMuon")
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }
    
    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NhanVien")
    public NhanVien getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NgayMuon", length=23)
    public Date getNgayMuon() {
        return this.ngayMuon;
    }
    
    public void setNgayMuon(Date ngayMuon) {
        this.ngayMuon = ngayMuon;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NgayTra", length=23)
    public Date getNgayTra() {
        return this.ngayTra;
    }
    
    public void setNgayTra(Date ngayTra) {
        this.ngayTra = ngayTra;
    }

    
    @Column(name="SoLuongSach")
    public Integer getSoLuongSach() {
        return this.soLuongSach;
    }
    
    public void setSoLuongSach(Integer soLuongSach) {
        this.soLuongSach = soLuongSach;
    }

    
    @Column(name="TinhTrangMuon")
    public Integer getTinhTrangMuon() {
        return this.tinhTrangMuon;
    }
    
    public void setTinhTrangMuon(Integer tinhTrangMuon) {
        this.tinhTrangMuon = tinhTrangMuon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phieuMuon")
    public Set<ChiTietPhieuMuon> getChiTietPhieuMuons() {
        return this.chiTietPhieuMuons;
    }
    
    public void setChiTietPhieuMuons(Set<ChiTietPhieuMuon> chiTietPhieuMuons) {
        this.chiTietPhieuMuons = chiTietPhieuMuons;
    }




}


