package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name="Sach"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class Sach  implements java.io.Serializable {


     private int maSach;
     private DanhMuc danhMuc;
     private NhaXuatBan nhaXuatBan;
     private TacGia tacGia;
     private Serializable tenSach;
     private Serializable nhanDeChinh;
     private Serializable nhanDePhu;
     private Date namXuatBan;
     private Serializable tinhTrangSach;
     private Boolean tinhTrangMuon;
     private Double giaSach;
     private Serializable kichThuoc;
     private Serializable ngonNgu;
     private Integer cuon;
     private Integer tap;
     private Serializable xemTruoc;
     private String tomTat;
     private Set<ChiTietPhieuMuon> chiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>(0);

    public Sach() {
    }

	
    public Sach(int maSach) {
        this.maSach = maSach;
    }
    public Sach(int maSach, DanhMuc danhMuc, NhaXuatBan nhaXuatBan, TacGia tacGia, Serializable tenSach, Serializable nhanDeChinh, Serializable nhanDePhu, Date namXuatBan, Serializable tinhTrangSach, Boolean tinhTrangMuon, Double giaSach, Serializable kichThuoc, Serializable ngonNgu, Integer cuon, Integer tap, Serializable xemTruoc, String tomTat, Set<ChiTietPhieuMuon> chiTietPhieuMuons) {
       this.maSach = maSach;
       this.danhMuc = danhMuc;
       this.nhaXuatBan = nhaXuatBan;
       this.tacGia = tacGia;
       this.tenSach = tenSach;
       this.nhanDeChinh = nhanDeChinh;
       this.nhanDePhu = nhanDePhu;
       this.namXuatBan = namXuatBan;
       this.tinhTrangSach = tinhTrangSach;
       this.tinhTrangMuon = tinhTrangMuon;
       this.giaSach = giaSach;
       this.kichThuoc = kichThuoc;
       this.ngonNgu = ngonNgu;
       this.cuon = cuon;
       this.tap = tap;
       this.xemTruoc = xemTruoc;
       this.tomTat = tomTat;
       this.chiTietPhieuMuons = chiTietPhieuMuons;
    }
   
     @Id 

    
    @Column(name="MaSach", unique=true, nullable=false)
    public int getMaSach() {
        return this.maSach;
    }
    
    public void setMaSach(int maSach) {
        this.maSach = maSach;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaDanhMuc")
    public DanhMuc getDanhMuc() {
        return this.danhMuc;
    }
    
    public void setDanhMuc(DanhMuc danhMuc) {
        this.danhMuc = danhMuc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NhaXuatBan")
    public NhaXuatBan getNhaXuatBan() {
        return this.nhaXuatBan;
    }
    
    public void setNhaXuatBan(NhaXuatBan nhaXuatBan) {
        this.nhaXuatBan = nhaXuatBan;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TacGia")
    public TacGia getTacGia() {
        return this.tacGia;
    }
    
    public void setTacGia(TacGia tacGia) {
        this.tacGia = tacGia;
    }

    
    @Column(name="TenSach")
    public Serializable getTenSach() {
        return this.tenSach;
    }
    
    public void setTenSach(Serializable tenSach) {
        this.tenSach = tenSach;
    }

    
    @Column(name="NhanDeChinh")
    public Serializable getNhanDeChinh() {
        return this.nhanDeChinh;
    }
    
    public void setNhanDeChinh(Serializable nhanDeChinh) {
        this.nhanDeChinh = nhanDeChinh;
    }

    
    @Column(name="NhanDePhu")
    public Serializable getNhanDePhu() {
        return this.nhanDePhu;
    }
    
    public void setNhanDePhu(Serializable nhanDePhu) {
        this.nhanDePhu = nhanDePhu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NamXuatBan", length=10)
    public Date getNamXuatBan() {
        return this.namXuatBan;
    }
    
    public void setNamXuatBan(Date namXuatBan) {
        this.namXuatBan = namXuatBan;
    }

    
    @Column(name="TinhTrangSach")
    public Serializable getTinhTrangSach() {
        return this.tinhTrangSach;
    }
    
    public void setTinhTrangSach(Serializable tinhTrangSach) {
        this.tinhTrangSach = tinhTrangSach;
    }

    
    @Column(name="TinhTrangMuon")
    public Boolean getTinhTrangMuon() {
        return this.tinhTrangMuon;
    }
    
    public void setTinhTrangMuon(Boolean tinhTrangMuon) {
        this.tinhTrangMuon = tinhTrangMuon;
    }

    
    @Column(name="GiaSach", precision=53, scale=0)
    public Double getGiaSach() {
        return this.giaSach;
    }
    
    public void setGiaSach(Double giaSach) {
        this.giaSach = giaSach;
    }

    
    @Column(name="KichThuoc")
    public Serializable getKichThuoc() {
        return this.kichThuoc;
    }
    
    public void setKichThuoc(Serializable kichThuoc) {
        this.kichThuoc = kichThuoc;
    }

    
    @Column(name="NgonNgu")
    public Serializable getNgonNgu() {
        return this.ngonNgu;
    }
    
    public void setNgonNgu(Serializable ngonNgu) {
        this.ngonNgu = ngonNgu;
    }

    
    @Column(name="Cuon")
    public Integer getCuon() {
        return this.cuon;
    }
    
    public void setCuon(Integer cuon) {
        this.cuon = cuon;
    }

    
    @Column(name="Tap")
    public Integer getTap() {
        return this.tap;
    }
    
    public void setTap(Integer tap) {
        this.tap = tap;
    }

    
    @Column(name="XemTruoc")
    public Serializable getXemTruoc() {
        return this.xemTruoc;
    }
    
    public void setXemTruoc(Serializable xemTruoc) {
        this.xemTruoc = xemTruoc;
    }

    
    @Column(name="TomTat")
    public String getTomTat() {
        return this.tomTat;
    }
    
    public void setTomTat(String tomTat) {
        this.tomTat = tomTat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sach")
    public Set<ChiTietPhieuMuon> getChiTietPhieuMuons() {
        return this.chiTietPhieuMuons;
    }
    
    public void setChiTietPhieuMuons(Set<ChiTietPhieuMuon> chiTietPhieuMuons) {
        this.chiTietPhieuMuons = chiTietPhieuMuons;
    }




}


