package model;
// Generated 11-Dec-2014 21:24:01 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TacGia generated by hbm2java
 */
@Entity
@Table(name="TacGia"
    ,schema="dbo"
    ,catalog="QuanLyThuVien"
)
public class TacGia  implements java.io.Serializable {


     private int maTacGia;
     private Serializable tenTacGia;
     private Serializable quocTich;
     private Date namSinh;
     private Serializable tenVietTat;
     private Set<Sach> saches = new HashSet<Sach>(0);

    public TacGia() {
    }

	
    public TacGia(int maTacGia) {
        this.maTacGia = maTacGia;
    }
    public TacGia(int maTacGia, Serializable tenTacGia, Serializable quocTich, Date namSinh, Serializable tenVietTat, Set<Sach> saches) {
       this.maTacGia = maTacGia;
       this.tenTacGia = tenTacGia;
       this.quocTich = quocTich;
       this.namSinh = namSinh;
       this.tenVietTat = tenVietTat;
       this.saches = saches;
    }
   
     @Id 

    
    @Column(name="MaTacGia", unique=true, nullable=false)
    public int getMaTacGia() {
        return this.maTacGia;
    }
    
    public void setMaTacGia(int maTacGia) {
        this.maTacGia = maTacGia;
    }

    
    @Column(name="TenTacGia")
    public Serializable getTenTacGia() {
        return this.tenTacGia;
    }
    
    public void setTenTacGia(Serializable tenTacGia) {
        this.tenTacGia = tenTacGia;
    }

    
    @Column(name="QuocTich")
    public Serializable getQuocTich() {
        return this.quocTich;
    }
    
    public void setQuocTich(Serializable quocTich) {
        this.quocTich = quocTich;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NamSinh", length=10)
    public Date getNamSinh() {
        return this.namSinh;
    }
    
    public void setNamSinh(Date namSinh) {
        this.namSinh = namSinh;
    }

    
    @Column(name="TenVietTat")
    public Serializable getTenVietTat() {
        return this.tenVietTat;
    }
    
    public void setTenVietTat(Serializable tenVietTat) {
        this.tenVietTat = tenVietTat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tacGia")
    public Set<Sach> getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set<Sach> saches) {
        this.saches = saches;
    }




}


